trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
- name: SolutionBaseName
  value: SFA.DAS.Apim.Developer.Api
- name: DACPACSolutionBaseName
  value: SFA.DAS.Apim.Developer.Database
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.3.31
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)
  - template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
    parameters:
      SolutionBaseName: $(DACPACSolutionBaseName)
      SqlProjectPath: src/SFA.DAS.Apim.Developer.Database/SFA.DAS.Apim.Developer.Database.sqlproj
