parameters:
- name: RunBlockOnPossibleDataLoss
  displayName: Add /p:BlockOnPossibleDataLoss=false argument to DACPAC deployment
  type: boolean
  default: false

trigger:
  batch: true
  branches:
    include:
      - "*"

variables:
- name: SolutionBaseName
  value: SFA.DAS.Apim.Developer.Api
- name: DACPACSolutionBaseName
  value: SFA.DAS.Apim.Developer.Database
- name: BuildConfiguration
  value: release
- name: BuildPlatform
  value: any cpu
- group: RELEASE Management Resources
- group: RELEASE das-apim-developer-api
- name: Deploy
  value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.10
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/4.5.0
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: DASD-9049-apim-developer-api

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)
  - template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
    parameters:
      SolutionBaseName: $(DACPACSolutionBaseName)
      SqlProjectPath: src/SFA.DAS.Apim.Developer.Database/SFA.DAS.Apim.Developer.Database.sqlproj

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  condition: and(succeeded(), eq(variables.Deploy, 'true'))  
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM
      RunBlockOnPossibleDataLoss: ${{ parameters.RunBlockOnPossibleDataLoss }}

- stage: Deploy_TEST
  dependsOn: Build
  displayName: Deploy to TEST
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: DevTest Management Resources
  - group: TEST DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST
      ServiceConnection: SFA-DAS-DevTest-ARM
      RunBlockOnPossibleDataLoss: ${{ parameters.RunBlockOnPossibleDataLoss }}

- stage: Deploy_TEST2
  dependsOn: Build
  displayName: Deploy to TEST2
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: DevTest Management Resources
  - group: TEST2 DevTest Shared Resources
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: TEST2
      ServiceConnection: SFA-DAS-DevTest-ARM
      RunBlockOnPossibleDataLoss: ${{ parameters.RunBlockOnPossibleDataLoss }}