CREATE TABLE [dbo].[ApimUser]
(
    [ApimUserId] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [InternalUserId] VARCHAR(50) NOT NULL,
    [ApimUserTypeId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES ApimUserType(Id)
)
