
using System;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;
using SFA.DAS.Apim.Developer.Domain.Configuration;
using SFA.DAS.Apim.Developer.Domain.Entities;
using SFA.DAS.Apim.Developer.Domain.Interfaces;
using SFA.DAS.Apim.Developer.Domain.Subscriptions.Api;

namespace SFA.DAS.Apim.Developer.Application.AzureApimManagement.Services
{
    public class SubscriptionService : ISubscriptionService
    {
        private readonly IAzureApimManagementService _azureApimManagementService;
        private readonly IApimUserRepository _apimUserRepository;
        private readonly IApimUserTypeRepository _apimUserTypeRepository;
        private readonly IOptions<ApimResourceConfiguration> _apimResourceConfig;

        public SubscriptionService(IAzureApimManagementService azureApimManagementService, IApimUserRepository apimUserRepository, IApimUserTypeRepository apimUserTypeRepository)
        {
            _azureApimManagementService = azureApimManagementService;
            _apimUserRepository = apimUserRepository;
            _apimUserTypeRepository = apimUserTypeRepository;
        }

        public async Task<string> CreateUserSubscription(string internalUserId, string apimUserTypeName, string productName)
        {
            var apimUserType = await _apimUserTypeRepository.Get(apimUserTypeName);
            var apimUser = await _apimUserRepository.GetByInternalIdAndType(internalUserId, apimUserType.Id);
            if (apimUser == null)
            {
                var newUser = new ApimUser
                {
                    ApimUserId = new Guid(), // TODO: should this be generated by SQL?
                    ApimUserTypeId = apimUserType.Id,
                    InternalUserId = internalUserId
                };
                var newApimUser = await CreateApimUser(newUser);
                apimUser = await _apimUserRepository.Insert(newUser);
            }
            var subscriptionId = $"{apimUserType.Name}-{internalUserId}"; //TODO: think about this more, maybe just another guid?
            var createSubscriptionRequest = new CreateSubscriptionRequest(subscriptionId, apimUser.ApimUserId.ToString(), productName);
            var response = await _azureApimManagementService.Put<CreateSubscriptionResponse>(createSubscriptionRequest);

            return subscriptionId;
        }

        private async Task<Guid> CreateApimUser(ApimUser apimUser)
        {
            var newUserRequest = new CreateUserRequest(apimUser.ApimUserId.ToString());
            var apimUserResponse = await _azureApimManagementService.Put<CreateUserResponse>(newUserRequest);
            return Guid.Parse(apimUserResponse.Body.Name);
        }
    }
}